### ISSUE TITLE
Fail to build tiny-dpcpp-nn on linux, libtorch not found

### ISSUE THREAD

**Issue by shinnits** [intel/tiny-dpcpp-nn#8]
When building tiny-dpcpp-nn, pip install by using setup.py in dpcpp_binding/,
it will hang at  libtorch not found

>
  -- Found IPEX: /opt/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/lib/libintel-ext-pt-cpu.so;/opt/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/lib/libintel-ext-pt-gpu.so
  -- libtorch not found in /noc/build/tiny-dpcpp-nn/extern/. Downloading...

Ubuntu version:22.04

**Comment by Yunaik** [comment]
Can you try directly downloading it from here: https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.1.10%2bxpu&os=linux%2fwsl2&package=cppsdk?

**Comment by shinnits** [comment]
Sure, many thanks for the advice!
